### ISSUE TITLE
MVP Finishing Touches

### ISSUE THREAD

**Issue by matthewmain** [matthewmain/kiss_the_sky#105]
- [x] Remove logo's link to home screen (will prevent exiting game accidentally)
- [x] [Light mode logo](https://dzwonsemrish7.cloudfront.net/items/0D3L1T00452b1i0n3b0J/Image%202019-07-29%20at%206.17.22%20PM.png) needs to switch to [white background logo](https://github.com/matthewmain/kiss_the_sky/blob/master/webapp/client/public/assets/title_header_light.svg)
- [x] Handle light mode in non-game screens 
- [x] Update [menu border/shadow](https://dzwonsemrish7.cloudfront.net/items/2S1e1s0t051v2q3W3L1v/Image%202019-07-29%20at%206.21.06%20PM.png)
- [x] Fix fonts
- [x] START > blank screen with resume button bug. 
- [x] Finalize default speed: render either every 3 physics iterations.
- [x] Replace dotted zeroes throughout leaderboard & dashboards.
- [x] Fix seasons hanging on resume game issue.
- [x] Remove level and percentage from Ambient mode saves in Saved Sessions.
- [x] Remove periods after ranking numbers on My High Scores.
- [x] Add direct links to leaderboard on My High Scores.
- [x] Finish styling My High Scores.
- [x] menu icon animation.
~Prod resuming saved game without header/footer~

**Comment by robbobfrh84** [comment]
Is https://kissthesky.app/ working for you? It's not loading for me. 
- It works with `www` though.. at https://www.kissthesky.app

**Comment by matthewmain** [comment]
Sadly, had to give up "https://kissthesky.app/" to handle email forwarding. (Apparently that's what handles "@" emails, so you can't use the domain for emails if you're using that format to host the sight. Who knew.) So, yeah, we're sitting on "https://www.kissthesky.app" instead. BUT it redirects from just "kissthesky.app" now. So we should be able to just give anyone that stripped down URL and they'll access the site.

**Comment by robbobfrh84** [comment]
![Screen Shot 2019-07-30 at 3 13 32 PM](https://user-images.githubusercontent.com/15821138/62161975-e077af00-b2dc-11e9-956b-5f067b01aadf.png)
Ok, this doesn't happen if you just go to the root/landing page and play. for me in development mode it WILL

... if I go to dashboard/leaderboard etc... and click the new start button. 
... So, i think it's a react side issue. probably not toggleding the game entirely... or in correct order, or something I'll look into this.

**Comment by matthewmain** [comment]
I think the only issue is that it's getting automatically paused somewhere when the dashboard gets pulled up. Try just running `window.resume()` on the start button click. I bet that'll fix it.

**Comment by robbobfrh84** [comment]
Ya I think that’ll do it!

**Comment by matthewmain** [comment]
Scratch that, no need to run `window.resume()` with the start button anymore. I just updated the game initiation to automatically force unpause at the beginning. So this will fix any issues with the game being paused/blank after hitting the "sow" button, regardless of where you've navigated beforehand. | PR: https://github.com/matthewmain/kiss_the_sky/pull/110

**Comment by robbobfrh84** [comment]
Is the `menu icon animation` related to the safari issue? If not, i'll add that to my todo 
cards

**Comment by matthewmain** [comment]
That one is building a new animated hamburger icon that morphs into an arrow on click. Not really "mvp", but it's my carrot for finishing all the boring stuff, lol. I'm halfway done with it, was working on it on my flight to Rome--have actually been wanting to practice custom svg/javascript animations.

On the other hand, the "Prod resuming saved game without header/footer?" one has me a little stumped. On prod, whenever you start a saved game, the header/footer is invisible until you hit play. (This doesn't happen on dev at all.) Running `updateUI()` resolves it perfectly. But I haven't been able to find anywhere to run it in the code so that it gets called after the resume game is pulled up. If you know off-hand of some callback that can run `updateUI()` in the React after the resumed game data is loaded, let me know.

**Comment by matthewmain** [comment]
Just going to move that "Prod resuming saved game without header/footer?" item from MVP and open an issue for it instead that we can address later. It's pretty minor, something I think we can probably live with for the MVP.
